<?= view('admin/reports/respon_mahasiswa', [
    'title'                     => $title ?? 'Laporan FGD',
    'link'                      => $link,
    'responses'                 => $responses,
    'summary'                   => $summary,
    'items'                     => $items,
    'textAnswers'               => $textAnswers ?? [],
    'comments'                  => $comments,
    'respondentSectionTitle'    => 'Identitas Peserta FGD',
    'scoreSectionTitle'         => 'Rekap Skor Butir FGD',
    'textSectionTitle'          => 'Tanggapan dan Masukan FGD Non-Skala',
    'commentsSectionTitle'      => 'Rekomendasi/Catatan Peserta FGD',
    'itemColumnLabel'           => 'Topik/Butir Diskusi',
    'respondentColumnLabel'     => 'Peserta FGD',
    'generalCommentColumnLabel' => 'Kesimpulan dan Rekomendasi Umum FGD',
]) ?>
