<?= view('admin/reports/respon_mahasiswa', [
    'title'                     => $title ?? 'Laporan Observasi',
    'link'                      => $link,
    'responses'                 => $responses,
    'summary'                   => $summary,
    'items'                     => $items,
    'textAnswers'               => $textAnswers ?? [],
    'comments'                  => $comments,
    'respondentSectionTitle'    => 'Identitas Observer',
    'scoreSectionTitle'         => 'Rekap Skor Butir Observasi',
    'textSectionTitle'          => 'Hasil Observasi Non-Skala',
    'commentsSectionTitle'      => 'Catatan Observer per Butir',
    'itemColumnLabel'           => 'Butir/Kriteria Observasi',
    'respondentColumnLabel'     => 'Observer',
    'generalCommentColumnLabel' => 'Catatan Observasi Umum',
]) ?>
