<?= view('admin/reports/respon_mahasiswa', [
    'title'                     => $title ?? 'Laporan Tes Kinerja',
    'link'                      => $link,
    'responses'                 => $responses,
    'summary'                   => $summary,
    'items'                     => $items,
    'textAnswers'               => $textAnswers ?? [],
    'comments'                  => $comments,
    'respondentSectionTitle'    => 'Identitas Peserta/Mahasiswa dan Penilai',
    'scoreSectionTitle'         => 'Rekap Skor Rubrik Kinerja',
    'textSectionTitle'          => 'Deskripsi Kinerja Non-Skala',
    'commentsSectionTitle'      => 'Catatan Penilai per Kriteria',
    'itemColumnLabel'           => 'Rubrik/Kriteria Kinerja',
    'respondentColumnLabel'     => 'Peserta/Penilai',
    'generalCommentColumnLabel' => 'Catatan Umum Penilaian',
]) ?>
